//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compartment.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string COM_PORT {
            get {
                return ((string)(this["COM_PORT"]));
            }
            set {
                this["COM_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public string COM_BAUDRATE {
            get {
                return ((string)(this["COM_BAUDRATE"]));
            }
            set {
                this["COM_BAUDRATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string COM_DATA_BIT_LENGTH {
            get {
                return ((string)(this["COM_DATA_BIT_LENGTH"]));
            }
            set {
                this["COM_DATA_BIT_LENGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string COM_STOP_BIT_LENGTH {
            get {
                return ((string)(this["COM_STOP_BIT_LENGTH"]));
            }
            set {
                this["COM_STOP_BIT_LENGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NONE")]
        public string COM_PARITY {
            get {
                return ((string)(this["COM_PARITY"]));
            }
            set {
                this["COM_PARITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IS_EXIT_ERROR_IO_BOARD {
            get {
                return ((bool)(this["IS_EXIT_ERROR_IO_BOARD"]));
            }
            set {
                this["IS_EXIT_ERROR_IO_BOARD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IS_CHECK_SERIAL_OPENED {
            get {
                return ((bool)(this["IS_CHECK_SERIAL_OPENED"]));
            }
            set {
                this["IS_CHECK_SERIAL_OPENED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IS_DOOR_RECOVER_ENABLE {
            get {
                return ((bool)(this["IS_DOOR_RECOVER_ENABLE"]));
            }
            set {
                this["IS_DOOR_RECOVER_ENABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IS_LEVER_RECOVER_ENABLE {
            get {
                return ((bool)(this["IS_LEVER_RECOVER_ENABLE"]));
            }
            set {
                this["IS_LEVER_RECOVER_ENABLE"] = value;
            }
        }
    }
}
